# Default values for vault-feature-fit-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: vault-feature-fit
serviceName: vault-feature-fit-svc

revisionHistoryLimit: 10
containerPort: 3000
servicePort: 3000
portName: port-http
namespace: default

service:
  type: NodePort

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  name: vault-feature-fit

hpa:
  min: 4
  max: 4
  utilization:
    cpu: 75
    memory: 75

env:
  node: production
  clearbanc: development

gcloud:
  projectId: clearbanc-api-dev
  region: us-central1
